name: Build NuGet package

on:
  push:
    tags:
      - v*

jobs:
  build_native_assets:
    name: Build native assets
    uses: ./.github/workflows/build-onigwrap.yml
  build:
    needs: build_native_assets
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Prepare version string
        id: version
        env:
          TAG: ${{ github.ref_name }}
        run: echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Download runtimes
        uses: actions/download-artifact@v4
        with:
          name: runtimes
          path: runtimes
      - name: Restore project
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release -p:Version="${{ steps.version.outputs.version }}" --no-restore
      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity normal
      - name: Pack
        run: dotnet pack -c Release -o .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Onigwrap.${{ steps.version.outputs.version }}
          path: Onigwrap.${{ steps.version.outputs.version }}.nupkg
